# Generated by Django 5.1.6 on 2025-02-21 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifications',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='Alvand.users'),
        ),
    ]
