# Generated by Django 5.1.6 on 2025-02-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0002_alter_verifications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=191, verbose_name='نام کاربری:'),
        ),
    ]
