# Generated by Django 5.1.6 on 2025-03-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0009_remove_users_internal_alter_infos_educationdegree_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
