# Generated by Django 5.1.6 on 2025-03-03 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0013_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device',
            field=models.CharField(choices=[('KX-TA 308', 'KX-TA 308'), ('KX-TES 824', 'KX-TES 824'), ('KX-TEM 824', 'KX-TEM 824')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
