# Generated by Django 5.1.6 on 2025-03-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0016_alter_costs_hamrahaval_alter_costs_international_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsending',
            name='emailtosend',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emailsending',
            name='lines',
            field=models.IntegerField(default=1),
        ),
    ]
