# Generated by Django 5.1.6 on 2025-03-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0017_alter_emailsending_emailtosend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsending',
            name='lines',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
    ]
