# Generated by Django 5.1.6 on 2025-03-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0018_alter_emailsending_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='errorsreport',
            field=models.BooleanField(default=False),
        ),
    ]
