# Generated by Django 5.1.6 on 2025-03-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0022_errorssent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='errorsSent',
        ),
    ]
