# Generated by Django 5.1.6 on 2025-03-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0024_errorssent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorssent',
            name='fault',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alvand.faults'),
        ),
    ]
