# Generated by Django 5.1.6 on 2025-04-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0027_externaldbinfos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='externalDBInfos',
        ),
    ]
