# Generated by Django 5.1.6 on 2025-04-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0029_lices_version_alter_device_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cableType',
            field=models.CharField(blank=True, choices=[('rs-232c', 'RS-232C'), ('ethernet', 'Ethernet')], null=True),
        ),
    ]
