# Generated by Django 5.1.6 on 2025-04-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0032_rename_cable_type_device_cabletype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='cableType',
            new_name='cable_type',
        ),
    ]
