# Generated by Django 5.1.4 on 2025-06-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0035_users_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='groupname',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='نقش:'),
        ),
    ]
