# Generated by Django 5.1.4 on 2025-07-19 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0036_infos_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='errors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
