# Generated by Django 5.1.4 on 2025-07-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0037_alter_errors_created_at_alter_errors_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='needs_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
