# Generated by Django 5.2.8 on 2025-12-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0040_supportmessage_alter_records_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infos',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'مرد'), (1, 'زن'), (2, 'نامعلوم')], null=True, verbose_name='جنسیت:'),
        ),
        migrations.AlterModelTable(
            name='records',
            table='alvand_records',
        ),
    ]
