# Generated by Django 5.2.8 on 2025-12-23 14:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alvand', '0041_alter_infos_gender_alter_records_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cable_type',
            field=models.CharField(blank=True, choices=[('rs-232c', 'RS-232C'), ('ethernet', 'ETHERNET')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='exts_label',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='records',
            name='transferring',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='users',
            name='usersextension',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None, verbose_name='دسترسی های داخلی:'),
        ),
    ]
